name = "Sphere"
version = "0.1.0"
defaultTargets = ["Sphere"]

[[lean_lib]]
name = "Sphere"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.25.2"

[[require]]
name = "Cochain"
git = "https://github.com/Chen2357/Cochain"
rev = "main"